services:
  selenium:
    image: selenium/standalone-firefox:latest
    expose:
      - 4444
      - 5900
    ports:
      - 4444
      - 5900
    healthcheck:
      test: [CMD, /opt/bin/check-grid.sh]
      timeout: 1s
      interval: 1s
      retries: 25
