[project]
name = "rd2weekly"
requires-python = ">=3.8"
version = "0.0.1"
dependencies = [
    "beautifulsoup4",
    "click",
    "docker",
    "selenium",
]

[tool.flake8]
max-line-length = 88

[tool.isort]
line_length = 88

[tool.mypy]
disallow_untyped_defs = true
